[workspace]
resolver = "2"
members = ["zhsh"]
default-members = ["zhsh"]

[workspace.package]
edition = "2021"
rust-version = "1.98"
license = "GPL-3.0-or-later"
repository = "https://github.com/zhshell/zhsh"

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "unwind"
